name: Grawkit Play Container Build
on: push
env:
  CONTAINER_NAME: ${{ github.repository_owner }}/grawkit-play
  CONTAINER_TAG: latest
jobs:
  build:
    runs-on: ubuntu-latest
    name: Container Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: play/Containerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: ${{ vars.CONTAINER_REGISTRY_URL }}/${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_TAG }}
